.TH t "1" "April 2012" "t" "User Commands"
.SH NAME
t \- language translation service from Google
.SH SYNOPSIS
.B t
[source] [target] [string]
.SH COPYRIGHT
Google Translate is a free statistical machine translation service provided by Google Inc.
.SH AVAILABILITY
bash, zsh
.SH DESCRIPTION
Bash wrapper to Google Translate website.
.SH LANGUAGE CODES
http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
.SH EXAMPLES
\fBt en pt "The World is Yours"\fR
.br
\fBt en zh "What's the Matrix?"\fR
.SH AUTHOR
Rainer Borene <https://github.com/rainerborene>
.SH SEE ALSO
wget, python
.P
Please file bugs at https://github.com/rainerborene/t/
